---
language: python
services: docker

env:
  global:
    - ROLE_NAME: icingaweb2
  matrix:
    - MOLECULE_IMAGE: "centos:centos8"
    - MOLECULE_IMAGE: "centos:centos7"
    - MOLECULE_IMAGE: "centos:centos6"
    - MOLECULE_IMAGE: "ubuntu:16.04"
    - MOLECULE_IMAGE: "ubuntu:18.04"
    - MOLECULE_IMAGE: "debian:10"

install:
  # Install test dependencies.
  - pip install molecule yamllint ansible-lint docker

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-$ROLE_NAME mkayontour.$ROLE_NAME
  - cd mkayontour.$ROLE_NAME

script:
  # Run tests.
  - molecule test
