---
- name: RedHat - Add Icinga 2 repository
  become: yes
  yum_repository:
    name: ICINGA-release
    description: Icinga packages for EL
    baseurl: "{{ icingaweb2_yum_url }}"
    gpgkey: "{{ icingaweb2_yum_key }}"
    gpgcheck: yes
  when: icingaweb2_manage_repository

- name: RedHat - Ensure EPEL is enabled
  become: yes
  yum:
    name: centos-release-scl-rh.noarch
    state: present
  when: icingaweb2_manage_centos_scl

- name: RedHat - Ensure icinga2 is installed
  become: yes
  yum:
    name: icingaweb2
    state: present
  notify: start httpd
  when: icingaweb2_manage_package
