---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance-${MOLECULE-IMAGE}
    image: ${MOLECULE-IMAGE}
    command: /sbin/init
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
verifier:
  name: testinfra
